import {mkdir,copyFile,readFile,writeFile} from 'node:fs/promises';
import {DECK} from './deck.mjs';
await mkdir('public',{recursive:true});
for(const f of ['index.html','card-meanings.html','style.css','magic-theme.css','app.mjs','meanings.mjs','deck.mjs','card-back.webp','_headers'])await copyFile(f,`public/${f}`);
await writeFile('public/.nojekyll','');
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prompts=`What new beginning deserves a small, practical experiment?|Which skill could you use immediately to make your intention concrete?|What could you learn by listening before deciding?|Where is care helping growth, and where might you need some yourself?|What boundary would offer stability without becoming too rigid?|Which shared rule fits your values, and which one deserves a closer look?|What choice would align your actions with what matters most?|What needs direction before you increase your speed?|Where would patient courage help more than pressure?|What could a quiet pause teach you before you reconnect?|How can you adapt to change while staying attentive to your choices?|What evidence or responsibility should you bring into this decision?|Would a different perspective help more than another attempt to force progress?|What ending might create space for a healthier next chapter?|Which adjustment could make this path sustainable?|Which attachment is shaping your choice, and how much freedom do you have?|What assumption has changed, and what would honest rebuilding require?|What would hope look like as a small daily practice?|Which parts of this uncertainty are facts and which are fears?|Where can you acknowledge something that is genuinely going well?|What deserves a fair review before you move forward?|What have you completed, and what will you carry into the next stage?|
What first step could give a new idea room to grow?|Which opportunity would expand your horizon without ignoring the plan?|What preparations would help you respond to an opening?|What achievement or gathering deserves recognition?|Which disagreement could become useful if everyone names the issue?|How can you receive recognition without depending on it?|What boundary deserves defending, and what argument can you leave alone?|What message needs a timely answer, and what needs more clarity?|What experience has made you resilient, and where do you need rest?|Which task can be shared, delayed, or set down?|What could you learn by exploring before committing?|How could bold energy be paired with a realistic follow-through?|Where could your confidence create room for someone else?|What vision could you communicate more clearly and collaboratively?|
What feeling is ready to be expressed with care?|Is the exchange genuinely mutual, and what conversation might help?|Which friendships or shared joys support you right now?|Does your lack of interest signal a mismatch, or a need to pause?|What remains available alongside a real disappointment?|What does nostalgia illuminate, and what might it conceal?|Which possibility survives a careful look at the facts?|What deeper need might explain a desire to leave?|Would the outcome you want satisfy the need beneath it?|What does everyday care contribute to your idea of belonging?|What gentle feeling or creative thought deserves a careful response?|What would consistent action add to an appealing emotional offer?|How can you show compassion while keeping your own boundary?|What would steady emotional honesty look like in this situation?|
What question could cut through confusion?|Which fact is missing from the choice you are avoiding?|What hurt needs acknowledgment before repair is possible?|What might rest clarify that more analysis cannot?|Is winning this disagreement worth its relational cost?|What would make a transition feel safer or more complete?|Where is discretion useful, and where might it become avoidance?|What small choice remains available inside a difficult situation?|Who could help you put a worry into perspective?|What exhausted pattern deserves a clear stopping point?|What can you verify before drawing a conclusion?|Would slowing down change the way your message lands?|How can you state a firm boundary without closing off useful information?|What standard would be fair to everyone involved?|
What practical first step would help you test an opportunity?|Which responsibility needs priority this week?|What specific feedback would improve the shared work?|Is protecting your resources providing stability or narrowing your options?|What material support or assistance is available to you?|Are the terms of giving and receiving clear and fair?|What return are you getting on your time and effort?|What deliberate practice would strengthen this skill?|Does your sense of independence match your actual resources?|What would make a shared plan durable over time?|What can you study or do today to advance a long-term goal?|Which routine supports progress, and which one needs updating?|How can you include your own resources in the care you provide?|What would responsible stewardship look like here?`.trim().split('|');
if(prompts.length!==78)throw new Error(`Need 78 learning prompts; got ${prompts.length}`);
const groups=[['Major Arcana','major-arcana','The major cards introduce broad themes such as change, choice, responsibility, and renewal. Their position helps you apply that theme to the question at hand.'],['Wands','wands','Wands invite attention to motivation, creative energy, ambition, and how an idea becomes action.'],['Cups','cups','Cups often bring feelings, connection, care, and emotional expectations into a reading.'],['Swords','swords','Swords bring thought, communication, conflict, and clarity into focus.'],['Pentacles','pentacles','Pentacles ask about work, resources, daily practices, and practical stability.']];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const library=groups.map(([name,id,description])=>`<section class="suit-section" id="${id}"><p class="eyebrow">${escape(name.toUpperCase())}</p><h2>${escape(name)}</h2><p>${escape(description)}</p><div class="entry-grid">${DECK.map((c,i)=>({c,i})).filter(({c})=>c.suit===name).map(({c,i})=>`<article class="meaning-entry" id="${slug(c.name)}" data-card="${escape(c.name.toLowerCase())}"><h3>${escape(c.name)}</h3><p><strong>Upright</strong> ${escape(c.upright)}</p><p><strong>Reversed</strong> ${escape(c.reversed)}</p><p class="practice-prompt"><strong>Ask yourself</strong> ${escape(prompts[i].trim())}</p></article>`).join('')}</div></section>`).join('');
const original=await readFile('index.html','utf8');
await writeFile('public/index.html',original);
const reference=(await readFile('card-meanings.html','utf8'))
  .replace('<meta name="theme-color" content="#101720">','<meta name="theme-color" content="#eee6f5">')
  .replace('<link rel="stylesheet" href="style.css">','<link rel="stylesheet" href="style.css"><link rel="stylesheet" href="magic-theme.css">')
  .replace('<!-- Filled at build time with all 78 card entries. -->',library);
await writeFile('public/card-meanings.html',reference);
// A self-contained, offline demo can be opened by double-clicking this file.
let html=original;
const art=(await readFile('card-back.webp')).toString('base64');
const css=((await readFile('style.css','utf8'))+'\n'+(await readFile('magic-theme.css','utf8'))).replace("url('card-back.webp')",`url('data:image/webp;base64,${art}')`);
const deck=(await readFile('deck.mjs','utf8')).replaceAll('export ','');
const app=(await readFile('app.mjs','utf8')).replace(/^import[^\n]+\n/,'').replace("if(location.protocol!=='file:'){try{const r=await fetch('/api/config');if(r.ok)state.config=await r.json();}catch{}}",'').replaceAll('card-meanings.html#','Tarot-Learning-Guild-Card-Meanings.html#');
html=html.replace('<link rel="stylesheet" href="style.css"><link rel="stylesheet" href="magic-theme.css">',`<style>${css}</style>`).replace('<script type="module" src="app.mjs"></script>',`<script>${deck}\n${app}</script>`);
html=html.replaceAll('href="card-meanings.html"','href="Tarot-Learning-Guild-Card-Meanings.html"');
await writeFile('Fifth-Card-Preview.html',html);
await writeFile('Tarot-Learning-Guild-Card-Meanings.html',reference.replace('<link rel="stylesheet" href="style.css">',`<style>${css}</style>`).replace('<script type="module" src="meanings.mjs"></script>',`<script>${await readFile('meanings.mjs','utf8')}</script>`).replaceAll('href="index.html', 'href="Tarot-Learning-Guild-Preview.html'));
