CREATE TABLE IF NOT EXISTS readings (
 id TEXT PRIMARY KEY, token_hash TEXT NOT NULL, topic TEXT NOT NULL,
 question TEXT NOT NULL, reversals INTEGER NOT NULL, deck TEXT NOT NULL,
 session_id TEXT UNIQUE, result TEXT, created INTEGER NOT NULL, expires INTEGER NOT NULL,
 is_free INTEGER NOT NULL DEFAULT 0,
 lock_until INTEGER NOT NULL DEFAULT 0, lease TEXT, attempts INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS readings_expiry ON readings(expires);
CREATE TABLE IF NOT EXISTS limits (id TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS free_quota (visitor_hash TEXT PRIMARY KEY, count INTEGER NOT NULL DEFAULT 0);
